# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'BLAlertDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for BLAlertDemo
  pod 'Masonry'

  pod 'Reveal-SDK', :configurations => ['Debug']

  target 'BLAlertDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'BLAlertDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
